version: '3.7'

services:
  app:
    # https://github.com/facebook/create-react-app/issues/8688
    # The stdin_open setting circumvents the above issue. Without this
    # setting, docker-compose up won't work as expected. I attempted
    # to downgrade react-scripts into version 3.4.0, and I attempted to
    # upgrade it into version 3.4.3, but neither route worked. Likely
    # the wrong version of react-scripts was installed, but I wasn't
    # able to understand why.
    stdin_open: true
    container_name: hobbies-helsinki
    build:
      context: .
      target: ${DOCKER_TARGET:-production}
      args:
        - NEXT_PUBLIC_CMS_GRAPHQL_ENDPOINT=${NEXT_PUBLIC_CMS_GRAPHQL_ENDPOINT}
        - NEXT_PUBLIC_EVENTS_GRAPHQL_ENDPOINT=${NEXT_PUBLIC_EVENTS_GRAPHQL_ENDPOINT}
        - NEXT_PUBLIC_LINKEDEVENTS_EVENT_ENDPOINT=${NEXT_PUBLIC_LINKEDEVENTS_EVENT_ENDPOINT}
        - NEXT_PUBLIC_APP_ORIGIN=${NEXT_PUBLIC_APP_ORIGIN}
        - NEXT_PUBLIC_MATOMO_SITE_ID=${NEXT_PUBLIC_MATOMO_SITE_ID}
        - NEXT_PUBLIC_MATOMO_ENABLED=${NEXT_PUBLIC_MATOMO_ENABLED}
        - NEXT_PUBLIC_ALLOW_UNAUTHORIZED_REQUESTS=${NEXT_PUBLIC_ALLOW_UNAUTHORIZED_REQUESTS}
        - NEXT_PUBLIC_SENTRY_ENVIRONMENT=${NEXT_PUBLIC_SENTRY_ENVIRONMENT}
        - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
        - NEXT_PUBLIC_SENTRY_TRACE_SAMPLE_RATE=${NEXT_PUBLIC_SENTRY_TRACE_SAMPLE_RATE}
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
        - NEXT_PUBLIC_DEBUG=${NEXT_PUBLIC_DEBUG}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    # At the time of writing this, .env.local is not working. Env variables have to be in .env file
    # if you are building production version locally in Docker
    env_file:
      - .env.local
